# Generated by Django 2.0.6 on 2018-06-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('done', models.BooleanField(default=False)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
